import Head from "next/head";
import { Container, Product, ProductDescription } from "../../../components";

const ProductPage = () => {
  return (
    <>
      <Head>
        <title>Malis.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-[calc(100vh-60px)] grid place-items-center">
        <Container>
          <div className="grid lg:grid-cols-2 gap-4">
            <Product />
            <ProductDescription />
          </div>
        </Container>
      </main>
    </>
  );
};

export default ProductPage;
