import Head from "next/head";
import Image from "next/image";
import { Container } from "../components";
import { MdOutlineDoubleArrow } from "react-icons/md";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Malis.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <section className="h-[calc(100vh-60px)] flex flex-col justify-evenly text-center">
            <h1 className="text-[40px] font-caption font-medium sm:text-[70px] md:text-[100px] lg:text-[135px]  ">
              Be Mini<span className="text-[#82AB2C]">malis</span>m.
            </h1>
            <div className="relative h-[300px] lg:h-[500px]">
              <Image
                src={"/landing-page-picutre-no-bg.webp"}
                alt="Minimalistic modern sofa"
                layout="fill"
                objectFit="cover"
                priority
              />
            </div>
            {/* CTA button used once through the application */}
            <Link passHref href="/shop/products">
              <a className="text-[18px] font-bold hover:text-gray-700 transition self-end mr-[10px] container:mr-0 flex items-center ">
                EXPLORE NOW <MdOutlineDoubleArrow />
              </a>
            </Link>
          </section>
        </Container>
      </main>
    </>
  );
}
